# Generated by Django 5.2.12 on 2026-03-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
